"""
ISCE2 Utilities
================
Helpers for generating stackSentinel.py configuration and validating
ISCE2 run files before and after processing.
"""

import logging
import subprocess
import sys
from pathlib import Path
from typing import List, Optional

logger = logging.getLogger(__name__)


def check_isce2_available() -> bool:
    """Return True if ISCE2's stackSentinel.py is on the PATH."""
    result = subprocess.run(
        ["which", "stackSentinel.py"],
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def build_stack_sentinel_cmd(
    slc_dir: Path,
    dem_file: Path,
    orbit_dir: Path,
    work_dir: Path,
    bbox_str: str,
    num_connections: int = 3,
    max_temp_baseline: int = 180,
    max_perp_baseline: int = 200,
    coregistration: str = "NESD",
    workflow: str = "interferogram",
    subswaths: Optional[List[str]] = None,
) -> List[str]:
    """
    Build the stackSentinel.py command-line argument list.

    Args:
        slc_dir:          Directory containing Sentinel-1 SAFE directories.
        dem_file:         Path to ISCE2-format DEM file (.wgs84 or .dem).
        orbit_dir:        Directory containing POEORB .EOF orbit files.
        work_dir:         ISCE2 working directory (configs + run_files go here).
        bbox_str:         Bounding box as "south north west east" string.
        num_connections:  Number of connections per node in the network.
        max_temp_baseline: Maximum temporal baseline in days.
        max_perp_baseline: Maximum perpendicular baseline in metres.
        coregistration:   Coregistration method — "NESD" or "geometry".
        workflow:          ISCE2 workflow type — "interferogram" or "slc".
        subswaths:        List of subswaths to process e.g. ["IW1", "IW2"].

    Returns:
        List of strings suitable for subprocess.run().
    """
    cmd = [
        "stackSentinel.py",
        "-s", str(slc_dir),
        "-d", str(dem_file),
        "-a", str(orbit_dir),
        "-b", bbox_str,
        "--num_connections", str(num_connections),
        "--coregistration", coregistration,
        "--workflow", workflow,
        "--useGPU",        # comment out if no CUDA GPU available
    ]

    if subswaths:
        cmd += ["--swath_num", " ".join(subswaths)]

    # stackSentinel.py must be run from the ISCE2 working directory
    logger.debug("stackSentinel.py command: %s", " ".join(cmd))
    return cmd


def get_run_files(run_dir: Path) -> List[Path]:
    """
    Return ISCE2 run files in execution order.

    stackSentinel.py generates files named run_01_unpack_slc_offset, etc.
    Sorting alphabetically gives the correct execution order.

    Args:
        run_dir: Path to the run_files directory.

    Returns:
        Sorted list of Path objects.
    """
    run_files = sorted(run_dir.glob("run_[0-9]*"))
    if not run_files:
        logger.warning("No run files found in %s", run_dir)
    return run_files


def check_step_done(work_dir: Path, step_name: str) -> bool:
    """
    Check if an ISCE2 processing step has already been completed.

    Creates a simple flag file in work_dir/.done/ to track completion.
    This enables resuming an interrupted run without reprocessing.

    Args:
        work_dir:  ISCE2 working directory.
        step_name: Name of the step (e.g. "run_01_unpack_slc_offset").

    Returns:
        True if the step's flag file exists.
    """
    done_dir = work_dir / ".done"
    done_dir.mkdir(parents=True, exist_ok=True)
    return (done_dir / f"{step_name}.done").exists()


def mark_step_done(work_dir: Path, step_name: str):
    """Write a flag file indicating a step has completed successfully."""
    done_dir = work_dir / ".done"
    done_dir.mkdir(parents=True, exist_ok=True)
    (done_dir / f"{step_name}.done").touch()
    logger.debug("Marked step done: %s", step_name)


def run_step(
    run_file: Path,
    work_dir: Path,
    log_path: Path,
    num_procs: int = 1,
    force: bool = False,
):
    """
    Execute a single ISCE2 run file, with checkpointing.

    Args:
        run_file:   Path to the shell run file generated by stackSentinel.py.
        work_dir:   ISCE2 working directory (execution happens here).
        log_path:   Path to the log file (appended to).
        num_procs:  Number of parallel processes (passed to step if supported).
        force:      If True, re-run even if the done flag exists.
    """
    step_name = run_file.stem

    if not force and check_step_done(work_dir, step_name):
        logger.info("Skipping completed step: %s", step_name)
        return

    logger.info("Running ISCE2 step: %s", step_name)

    cmd = ["bash", str(run_file)]
    if num_procs > 1:
        # Some run files accept --nproc; others ignore it — safe to pass anyway
        cmd += [f"--nproc={num_procs}"]

    with open(log_path, "a") as log_fh:
        result = subprocess.run(
            cmd,
            cwd=str(work_dir),
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            text=True,
        )

    if result.returncode != 0:
        logger.error(
            "ISCE2 step FAILED: %s (exit code %d). Check log: %s",
            step_name,
            result.returncode,
            log_path,
        )
        sys.exit(result.returncode)

    mark_step_done(work_dir, step_name)
    logger.info("Completed step: %s", step_name)
