#!/usr/bin/env python3
"""
05_run_isce2.py — Execute ISCE2 topsStack processing pipeline
=============================================================
Runs each ISCE2 run file generated by 04_prepare_isce2.py in order.
Implements checkpointing: completed steps are skipped on re-run, so
a failed or interrupted run can be resumed without reprocessing.

Processing stages (run files generated by stackSentinel.py):
    run_01  — Unpack SLC + offset
    run_02  — Average baseline
    run_03  — Extract bursts
    run_04  — Generate burst coherence (reference)
    run_05  — Coregister (geometry)
    run_06  — NESD coregistration ESD
    run_07  — Generate coherence
    run_08  — Generate interferograms
    run_09  — Filter and multilook
    run_10  — Unwrap (SNAPHU)
    run_11  — Geocode

Usage:
    python scripts/05_run_isce2.py --orbit asc  [--config config/project.cfg]
    python scripts/05_run_isce2.py --orbit desc [--config config/project.cfg]
    python scripts/05_run_isce2.py --orbit asc  --from-step run_10
    python scripts/05_run_isce2.py --orbit asc  --only-step run_10
    python scripts/05_run_isce2.py --orbit asc  --force  # re-run all steps

NOTE: This script can take 24-72 hours to complete. Consider running in a
      screen/tmux session:  screen -S isce2_asc
"""

import argparse
import logging
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from utils.geo_utils import load_config
from utils.isce2_utils import (
    check_isce2_available,
    get_run_files,
    run_step,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Execute ISCE2 topsStack run files with checkpointing"
    )
    parser.add_argument("--orbit",     required=True, choices=["asc", "desc"])
    parser.add_argument("--config",    default="config/project.cfg")
    parser.add_argument("--from-step", default=None,
                        help="Resume from this step name (e.g. run_08_interferogram)")
    parser.add_argument("--only-step", default=None,
                        help="Run only this single step")
    parser.add_argument("--force",     action="store_true",
                        help="Re-run all steps ignoring done flags")
    parser.add_argument("--nproc",     type=int, default=4,
                        help="Number of parallel processes per step (default: 4)")
    return parser.parse_args()


def main():
    args  = parse_args()
    orbit = args.orbit
    cfg   = load_config(args.config)

    if not check_isce2_available():
        logger.error(
            "ISCE2 not found on PATH. Install ISCE2 and activate your conda environment."
        )
        sys.exit(1)

    processing_dir = Path(cfg.get("paths", "processing_dir"))
    logs_dir       = Path(cfg.get("paths", "logs_dir"))

    work_dir  = processing_dir / "isce2" / orbit
    run_dir   = work_dir / "run_files"
    log_path  = logs_dir / f"isce2_{orbit}.log"

    if not run_dir.exists():
        logger.error(
            "Run files directory not found: %s\n"
            "Run 04_prepare_isce2.py --orbit %s first.",
            run_dir, orbit,
        )
        sys.exit(1)

    all_run_files = get_run_files(run_dir)
    if not all_run_files:
        logger.error("No run files found in %s", run_dir)
        sys.exit(1)

    # Filter run files based on --from-step or --only-step
    if args.only_step:
        run_files = [f for f in all_run_files if args.only_step in f.stem]
        if not run_files:
            logger.error("Step not found: %s", args.only_step)
            logger.error("Available: %s", [f.stem for f in all_run_files])
            sys.exit(1)
    elif args.from_step:
        from_names = [f.stem for f in all_run_files]
        start_idx  = next(
            (i for i, n in enumerate(from_names) if args.from_step in n), None
        )
        if start_idx is None:
            logger.error("Step not found: %s", args.from_step)
            logger.error("Available: %s", from_names)
            sys.exit(1)
        run_files = all_run_files[start_idx:]
    else:
        run_files = all_run_files

    logger.info(
        "Starting ISCE2 %s orbit pipeline: %d steps to run",
        orbit.upper(),
        len(run_files),
    )
    logger.info("Log file: %s", log_path)
    logger.info("Press Ctrl+C to pause — re-run the script to resume from last completed step.")

    start_time = time.time()

    for i, run_file in enumerate(run_files, 1):
        logger.info("[%d/%d] Step: %s", i, len(run_files), run_file.stem)
        step_start = time.time()

        run_step(
            run_file=run_file,
            work_dir=work_dir,
            log_path=log_path,
            num_procs=args.nproc,
            force=args.force,
        )

        elapsed = time.time() - step_start
        logger.info("Step done in %.1f min", elapsed / 60)

    total_elapsed = (time.time() - start_time) / 3600
    logger.info("ISCE2 %s orbit pipeline complete in %.1f hours", orbit.upper(), total_elapsed)

    print(f"\nISCE2 {orbit.upper()} processing complete.")
    print()
    print("QC checklist before proceeding:")
    print("  1. Open 3-5 interferograms in QGIS:")
    ifgram_dir = work_dir / "interferograms"
    print(f"     {ifgram_dir}")
    print("  2. Verify filt_fine.unw shows smooth fringes over the dam area.")
    print("  3. Verify filt_fine.cor shows coherence > 0.3 over rocky terrain.")
    print("  4. Check filt_fine.conncomp — large connected regions are good;")
    print("     many small fragments indicate unwrapping problems.")
    print()
    print(f"Next step: Edit config/mintpy_{orbit}.cfg to set the reference point.")
    print(f"           Then: python scripts/06_run_mintpy.py --orbit {orbit}")


if __name__ == "__main__":
    main()
