#!/usr/bin/env python3
"""
13_run_isce2_alos2.py — Execute ISCE2 stripmapStack pipeline for ALOS-2
=========================================================================
Runs each ISCE2 run file generated by 12_prepare_isce2_alos2.py in order.
Implements checkpointing: completed steps are skipped on re-run, so a failed
or interrupted run can be resumed without reprocessing from scratch.

ISCE2 stripmapStack stages for ALOS-2:
    run_01  — Focus SLCs (skipped if --nofocus was passed — Level 1.1 is pre-focused)
    run_02  — Compute temporal and spatial baselines
    run_03  — Estimate dense pixel offsets (coregistration)
    run_04  — Resample secondary SLCs to reference grid
    run_05  — Generate interferograms and apply multi-look
    run_06  — Filter and unwrap with SNAPHU (DEFO mode)
    run_07  — Geocode interferograms and geometry files

Outputs (in processing/isce2/alos2_asc/merged/):
    interferograms/<date1>_<date2>/
        filt_fine.unw         — unwrapped phase (radians, referenced to zero)
        filt_fine.cor         — interferometric coherence
        filt_fine.int         — complex interferogram
        filt_fine.unw.conncomp — connected components (SNAPHU)
    geom_reference/
        hgt.rdr               — DEM height in radar coordinates
        lat.rdr / lon.rdr     — latitude/longitude lookup tables
        los.rdr               — incidence + azimuth angles (2-band)
        shadowMask.rdr        — radar shadow mask

MintPy reads all of the above. After this step, run:
    python scripts/06_run_mintpy.py --orbit alos2_asc

Usage:
    python scripts/13_run_isce2_alos2.py
    python scripts/13_run_isce2_alos2.py --from-step run_06   # resume from unwrapping
    python scripts/13_run_isce2_alos2.py --only-step run_07   # re-run geocoding only
    python scripts/13_run_isce2_alos2.py --force              # re-run all steps

NOTE: This can take 12–48 hours depending on the number of scene pairs and
      available CPU/memory. Run in a screen/tmux session:
          screen -S isce2_alos2
          python scripts/13_run_isce2_alos2.py
"""

import argparse
import logging
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from utils.geo_utils import load_config
from utils.isce2_utils import (
    check_isce2_available,
    get_run_files,
    run_step,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

ORBIT_TAG = "alos2_asc"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Execute ISCE2 stripmapStack run files for ALOS-2 ascending pass"
    )
    parser.add_argument("--config",    default="config/project.cfg")
    parser.add_argument(
        "--from-step",
        default=None,
        help="Resume from this step name (e.g. run_06_filter_unwrap)",
    )
    parser.add_argument(
        "--only-step",
        default=None,
        help="Run only this single step",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-run all steps, ignoring existing completion flags",
    )
    parser.add_argument(
        "--nproc",
        type=int,
        default=4,
        help="Number of parallel processes per step (default: 4)",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    cfg  = load_config(args.config)

    # ISCE2 availability check — look for stripmapStack or any ISCE2 binary
    # (check_isce2_available looks for stackSentinel.py, so we do a broader check)
    result_check = __import__("subprocess").run(
        ["which", "stripmapStack.py"], capture_output=True, text=True
    )
    if result_check.returncode != 0 and not check_isce2_available():
        logger.error(
            "ISCE2 not found on PATH. Install ISCE2 and activate your conda environment."
        )
        sys.exit(1)

    processing_dir = Path(cfg.get("paths", "processing_dir"))
    logs_dir       = Path(cfg.get("paths", "logs_dir"))

    work_dir = processing_dir / "isce2" / ORBIT_TAG
    run_dir  = work_dir       / "run_files"
    log_path = logs_dir       / f"isce2_{ORBIT_TAG}.log"

    if not run_dir.exists():
        logger.error(
            "Run files directory not found: %s\n"
            "Run 12_prepare_isce2_alos2.py first.",
            run_dir,
        )
        sys.exit(1)

    all_run_files = get_run_files(run_dir)
    if not all_run_files:
        logger.error("No run files found in %s", run_dir)
        sys.exit(1)

    # Filter by --from-step / --only-step
    if args.only_step:
        run_files = [f for f in all_run_files if args.only_step in f.stem]
        if not run_files:
            logger.error("Step not found: %s", args.only_step)
            logger.error("Available: %s", [f.stem for f in all_run_files])
            sys.exit(1)
    elif args.from_step:
        from_names = [f.stem for f in all_run_files]
        start_idx  = next(
            (i for i, n in enumerate(from_names) if args.from_step in n),
            None,
        )
        if start_idx is None:
            logger.error("Step not found: %s", args.from_step)
            logger.error("Available: %s", from_names)
            sys.exit(1)
        run_files = all_run_files[start_idx:]
    else:
        run_files = all_run_files

    logger.info("ISCE2 ALOS-2 pipeline: %d steps to run", len(run_files))
    logger.info("Working directory: %s", work_dir)
    logger.info("Log file: %s", log_path)
    logger.info(
        "Press Ctrl+C to pause — re-run with --from-step <name> to resume."
    )

    logs_dir.mkdir(parents=True, exist_ok=True)
    start_time = time.time()

    for i, run_file in enumerate(run_files, 1):
        logger.info("[%d/%d] Step: %s", i, len(run_files), run_file.stem)
        step_start = time.time()

        run_step(
            run_file=run_file,
            work_dir=work_dir,
            log_path=log_path,
            num_procs=args.nproc,
            force=args.force,
        )

        elapsed = time.time() - step_start
        logger.info("Step done in %.1f min", elapsed / 60)

    total_elapsed = (time.time() - start_time) / 3600
    logger.info("ISCE2 ALOS-2 pipeline complete in %.1f hours", total_elapsed)

    # Print QC checklist
    merged_dir = work_dir / "merged"
    print(f"\nISCE2 ALOS-2 processing complete.")
    print()
    print("QC checklist before running MintPy:")
    print("  1. Check that interferograms were generated:")
    print(f"     ls {merged_dir}/interferograms/ | head -20")
    print("  2. Open 3–5 filt_fine.unw files in QGIS or with mdx.py:")
    print("     → Smooth fringes over the Brumadinho area = good unwrapping")
    print("     → Many small isolated regions = unwrapping failure (check coherence)")
    print("  3. Check coherence:")
    print("     → filt_fine.cor should be > 0.4 over rocky terrain")
    print("     → Tailings area may have lower coherence (expected for L-band)")
    print("  4. Check geometry files exist:")
    print(f"     ls {merged_dir}/geom_reference/")
    print("     → hgt.rdr, lat.rdr, lon.rdr, los.rdr, shadowMask.rdr")
    print()
    print("Next step:")
    print("  python scripts/06_run_mintpy.py --orbit alos2_asc")


if __name__ == "__main__":
    main()
